# Generated by Django 4.2.5 on 2023-09-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=30)),
                ('writer', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
