# Generated by Django 4.2.5 on 2023-09-29 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3three', 'Three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=6, null=True)),
                ('review', models.TextField(null=True, verbose_name='review movie')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(null=True, upload_to='media/movies'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='reviewmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movies'),
        ),
        migrations.AddField(
            model_name='favoritemovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movies'),
        ),
    ]
