# Generated by Django 4.2.5 on 2023-09-29 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movies_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
